### ISSUE TITLE
DSA cache control bit is not flush operation specific 

### ISSUE THREAD

**Issue by lplewa** [intel/DML#16]
Please update comments, or define cache-control flags for other operations. 

https://github.com/intel/DML/blob/2050879cc9aa35e0c6354517736b66e475a4e124/include/dml/dmldefs.h#L133

**Comment by abdelrahim-hentabli** [comment]
Hey @lplewa, with the most recent updates to dml with moving `DML_FLAG_PREFETCH_CACHE`, which is the DML defined cache-control flag, to be a shared flag.

And for `DML_FLAG_DONT_INVALIDATE_CACHE`, which is a use of the same value as cache-control, but is used in a different way exclusively for the cache flush operation, it remains a cache flush specific flag.

Does this solve your issue?

**Comment by mzhukova** [comment]
Closing as the issue was addressed, but no response for a few months. Please, feel free to re-open if necessary.
