### ISSUE TITLE
include/dml/detail/ml/buffer.hpp uses std::exchange but does not #include <utility>

### ISSUE THREAD

**Issue by fenrus75** [intel/DML#22]
/builddir/build/BUILD/DML-1.0.0/sources/c_api/../../include/dml/detail/ml/buffer.hpp:53:36: error: ‘exchange’ is not a member of ‘std’

std::exchange is in the utility header which isn't included

**Comment by mzhukova** [comment]
Hi @fenrus75 thanks for catching this! 
Could you let me know what compiler you were using?

**Comment by fenrus75** [comment]
fixed in pull request #23 

I'm using gcc 12 with latest glibc

**Comment by mzhukova** [comment]
Merged in https://github.com/intel/DML/commit/3d638bf9de4d5be803c8a66a4acf6037fe235184.
Please let me know if I can close the issue.

**Comment by fenrus75** [comment]
thanks for fixing!

**Comment by fenrus75** [comment]
btw somehow something went weird in the pull request since git munged the authorship of the patch ???
