### ISSUE TITLE
Incorrect handling of PAGE_FAULT_MASK

### ISSUE THREAD

**Issue by jposwiata** [intel/DML#29]
The condition in core_interconnect.cpp:138 is incorrect. Should be:
```
if (is_finished && (status & 0x7f) == page_fault_mask)
```
(to get rid of READ/WRITE page fault bit, 0x80).
Same in :107

**Comment by abdelrahim-hentabli** [comment]
Hey @jposwiata, thanks for opening this issue, and for sharing the fix as well. And great catch! We'll get this fixed ASAP!

**Comment by abdelrahim-hentabli** [comment]
Hey @jposwiata, thanks again for the issue, it should be fixed as of 673feec3d1a44351316845d90ff8f88df51904cc

**Comment by mzhukova** [comment]
Closing as resolved and no reply from the submitter for a month.
@jposwiata please, feel free to re-open if needed.
