### ISSUE TITLE
"404 page not found" for issue reporting link

### ISSUE THREAD

**Issue by bartlomiejgrzeskowiak** [intel/DML#35]
Link to [Issue Reporting](https://intel.github.io/DML/documentation/introduction_docs/issue_reporting.html) is wrong on
https://github.com/intel/DML/tree/develop#how-to-report-issues

**Comment by mzhukova** [comment]
Thanks for reporting it, I'll fix shortly.

**Comment by bartlomiejgrzeskowiak** [comment]
Done
