### ISSUE TITLE
A question about dml_finalize_job

### ISSUE THREAD

**Issue by Sean58238** [intel/DML#37]
In example code "multi_socket_example.c",  destroy a pointer but add a constant : "**jobs + SOCKET_COUNT**"
```
cleanup:
    for (uint32_t i = 0; i < SOCKET_COUNT; ++i)
    {
        dml_finalize_job(jobs + SOCKET_COUNT);
    }
```
why here is a constant , is not a variable offset for "**jobs + i**" 
```
cleanup:
    for (uint32_t i = 0; i < SOCKET_COUNT; ++i)
    {
        dml_finalize_job(jobs + i);
    }

**Comment by mzhukova** [comment]
Good catch, fix should be available in a bit.

**Comment by mzhukova** [comment]
@Sean58238 please check https://github.com/intel/DML/commit/47a92c336d9f164d18b7644c9d8c5d0bb414fc67 and let me know if this issues is resolved.

**Comment by Sean58238** [comment]
great,  thanks a lot!
