### ISSUE TITLE
CMake file bug: The .so file does not get a SONAME suffix

### ISSUE THREAD

**Issue by fenrus75** [intel/DML#5]
the shared library gets installed as /usr/lib64/libdml.so instead of /usr/lib64/libdml.so.1.0
this violates all linux standards and should be fixed (and prevents future compatibility managability)

**Comment by EgorKupaev** [comment]
Hi @fenrus75,

DML is a static library, so I suppose it shouldn't have soname.

From the cmake point of view, I think there will be no harm to add soname though.

**Comment by EgorKupaev** [comment]
The issue was fixed as part of [v0.1.4-beta](https://github.com/intel/DML/releases/tag/v0.1.4-beta)
