### ISSUE TITLE
documentation about delta operations on the hardware path

### ISSUE THREAD

**Issue by jannisko** [intel/DML#50]
According to the [docs](https://intel.github.io/DML/documentation/api_docs/high_level_api.html#create-delta-record), the hardware path for `create_delta` and `apply_delta` is not supported. The operation is available in the [DSA architecture specification](https://cdrdv2-public.intel.com/671116/341204-intel-data-streaming-accelerator-spec.pdf#%5B%7B%22num%22%3A226%2C%22gen%22%3A0%7D%2C%7B%22name%22%3A%22XYZ%22%7D%2C69%2C711%2C0%5D) tough. The [delta example](https://github.com/intel/DML/blob/develop/examples/high-level-api/delta_example.cpp) doesn't allow for the hardware path to be used, but modifying it to use it anyway runs without problem and leads to the right result, so the operation seems to work correctly on a surface level.

<details>
  <summary>modified example code</summary>

  ```cpp
#include <dml/dml.hpp>
#include <iostream>
#include <numeric>
#include <vector>

constexpr auto size = 1024u;  // 1 KB
constexpr auto delta_record_size = size * 10u / 8u;

template <typename path>
int execute_delta() {
    std::cout << "Starting dml::create_delta and dml::apply_delta example..." << std::endl;
    std::cout << "Create delta record of two 1KB memory_regions..." << std::endl;

    // Prepare data
    auto src1 = std::vector<std::uint8_t>(size);
    std::iota(src1.begin(), src1.end(), 0u);
    auto src2 = std::vector<std::uint8_t>(size);
    std::iota(src2.begin(), src2.end(), 1u);
    auto delta = std::vector<std::uint8_t>(delta_record_size, 0u);

    // Run operation
    auto create_result = dml::execute<path>(
        dml::create_delta, dml::make_view(src1), dml::make_view(src2), dml::make_view(delta));

    // Check result
    if (create_result.status == dml::status_code::ok) {
        std::cout << "Done. Next step..." << std::endl;
    }
    else {
        std::cout << "Failure occurred!" << std::endl;
        return -1;
    }

    std::cout << "Apply delta record to the first 1KB memory_region..." << std::endl;

    auto apply_result = dml::execute<path>(
        dml::apply_delta, dml::make_view(delta), dml::make_view(src1), create_result);

    // Check result
    if (apply_result.status == dml::status_code::ok) {
        std::cout << "Finished successfully!" << std::endl;
    }
    else {
        std::cout << "Failure occurred!" << std::endl;
        return -1;
    }

    if (src1 != src2) {
        std::cout << "But operation was done wrongly." << std::endl;
        return -1;
    }

    return 0;
}

int main(int argc, char **argv)
{
    return execute_delta<dml::hardware>();
}

  ``` 

</details>

Is there any documentation on why the feature is not supported? I'm guessing there are known edge cases for which it returns wrong results? Thanks!

**Comment by abdelrahim-hentabli** [comment]
Hey @jannisko there shouldn't be any edge cases where it generates wrong results. There just didn't exist a usecase/need to support this. It was supported up until very recently so it should still work fine, and we didn't remove the implementation, so it should still work perfectly fine.

We are just choosing to no longer support it moving forward, and so at some point it will "break", and we wanted to inform users about that now/ discourage users from using it as we don't know at what point it will no longer work.

**Comment by jannisko** [comment]
Thanks a lot for clarifying!
