### ISSUE TITLE
CMake file bug: libdmlhl.a gets installed in the wrong place

### ISSUE THREAD

**Issue by fenrus75** [intel/DML#6]
libdmlhl.a gets intalled into /usr/lib instead of /usr/lib64 (for system where libdir is lib64)

**Comment by EgorKupaev** [comment]
Hi @fenrus75,

Thanks for raising an issue, I will take a look onto install rules and make a proper change.

**Comment by fenrus75** [comment]
See the fix in pull request #8

**Comment by EgorKupaev** [comment]
The issue was fixed as part of [v0.1.4-beta](https://github.com/intel/DML/releases/tag/v0.1.4-beta)
